// 파트너 로고 파일 매핑 — content.json 등장 순서로 크롭한 결과다.
// 원본: 회사 제안서 덱의 로고 그리드 5장(2586x1166)을 격자 분할.
// 파일이 없는 이름은 자동으로 텍스트로 표시된다(폴백).
export const PARTNER_LOGO: Record<string, string> = {
  "NAVER": "/partners/logo-01.png",
  "Daum": "/partners/logo-02.png",
  "NATE": "/partners/logo-03.png",
  "kakao": "/partners/logo-04.png",
  "Google": "/partners/logo-05.png",
  "GOREALRA": "/partners/logo-06.png",
  "GORILLA": "/partners/logo-07.png",
  "KBS라디오 kong": "/partners/logo-08.png",
  "CBS RADIO": "/partners/logo-09.png",
  "CGV": "/partners/logo-10.png",
  "LOTTE CINEMA": "/partners/logo-11.png",
  "MEGABOX": "/partners/logo-12.png",
  "ACE Counter": "/partners/logo-13.png",
  "CPCGUARD": "/partners/logo-14.png",
  "Logger": "/partners/logo-15.png",
  "LOG": "/partners/logo-16.png",
  "ADMONSTER": "/partners/logo-17.png",
  "Colored Stone": "/partners/logo-18.png",
  "국세청": "/partners/logo-19.png",
  "중소기업청": "/partners/logo-20.png",
  "식품의약품안전처": "/partners/logo-21.png",
  "한국농어촌공사": "/partners/logo-22.png",
  "LH": "/partners/logo-23.png",
  "한국어촌어항협회": "/partners/logo-24.png",
  "에너지관리공단": "/partners/logo-25.png",
  "한국남부발전": "/partners/logo-26.png",
  "KNOC 한국석유공사": "/partners/logo-27.png",
  "수협": "/partners/logo-28.png",
  "중앙대학교": "/partners/logo-29.png",
  "동국대학교": "/partners/logo-30.png",
  "영남대학교": "/partners/logo-31.png",
  "부산디지털대학교": "/partners/logo-32.png",
  "SKYEDU": "/partners/logo-33.png",
  "페이스라인 성형외과": "/partners/logo-34.png",
  "BGN 밝은눈안과": "/partners/logo-35.png",
  "하늘안과의원": "/partners/logo-36.png",
  "하지 정맥류 네트워크": "/partners/logo-37.png",
  "헬레나의원": "/partners/logo-38.png",
  "끌림365": "/partners/logo-39.png",
  "롯데제과": "/partners/logo-40.png",
  "롯데리아": "/partners/logo-41.png",
  "동서식품": "/partners/logo-42.png",
  "SAMYANG": "/partners/logo-43.png",
  "천호식품": "/partners/logo-44.png",
  "L'OCCITANE": "/partners/logo-45.png",
  "Dr.Jart+": "/partners/logo-46.png",
  "isoi": "/partners/logo-47.png",
  "NATURE REPUBLIC": "/partners/logo-48.png",
  "THE FACE SHOP": "/partners/logo-49.png",
  "LG생활건강": "/partners/logo-50.png",
  "MEDIHEAL": "/partners/logo-51.png",
  "HOLIKA HOLIKA": "/partners/logo-52.png",
  "KATE TOKYO": "/partners/logo-53.png",
  "BRTC": "/partners/logo-54.png",
  "ANEW": "/partners/logo-55.png",
  "K2": "/partners/logo-56.png",
  "GIORDANO": "/partners/logo-57.png",
  "STCO": "/partners/logo-58.png",
  "MCM": "/partners/logo-59.png",
  "신한은행": "/partners/logo-60.png",
  "KB국민카드": "/partners/logo-61.png",
  "동부화재": "/partners/logo-62.png",
  "SC제일은행": "/partners/logo-63.png",
  "KEB하나은행": "/partners/logo-64.png",
  "pepper": "/partners/logo-65.png",
  "Cigna 라이나생명": "/partners/logo-66.png",
  "ING": "/partners/logo-67.png",
  "MG손해보험": "/partners/logo-68.png",
  "아주캐피탈": "/partners/logo-69.png",
  "월트디즈니": "/partners/logo-70.png",
  "GS리테일": "/partners/logo-71.png",
  "메이플스토리": "/partners/logo-72.png",
  "JEJU air": "/partners/logo-73.png",
  "B*Hands": "/partners/logo-74.png",
  "대명리조트": "/partners/logo-75.png",
  "Ford": "/partners/logo-76.png",
  "듀오": "/partners/logo-77.png",
  "동아제약": "/partners/logo-78.png",
};
